metrorail/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('railapp.urls')),
    path('accounts/',include('accounts.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

railapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('checkout/', views.checkout, name="checkout"),
    path('confirmation/', views.Confirmation, name="confirmation"),
    path('faq/', views.faq, name="faq"),
    path('userprofile/', views.userprofile, name="userprofile"),
    path('trainmasterprofile/', views.trainmasterprofile, name="trainmasterprofile"),
]

railapp/models.py
from django.db import models
from accounts.models import User

#Contact class for Contact Us page
class Contact(models.Model):
    name=models.CharField(max_length=200)
    email=models.EmailField()
    subject=models.TextField()
    def __str__(self):
         return self.name

#Question class for FAQ  page
class Question(models.Model):
    question = models.CharField(max_length=300)
    answered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    votesscore = models.IntegerField(default='0')
    amountofvotes = models.IntegerField(default='0')

    def __str__(self):
        return self.question

#Answer class for FAQ  page
class Answer(models.Model):
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE, blank=False, null=True)
    answer = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

#Question class for Announcement functionality
class Announcement(models.Model):
    title = models.CharField(max_length=200, unique=True)
    username = models.CharField(max_length=200)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    class Meta:
         ordering = ['created_on']

    def __str__(self):
        return self.title 

railapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponse
from .models import *
from railapp import models
from accounts.models import Book, GeneralUser
from django.core.exceptions import ObjectDoesNotExist

# function for the homepage.
def home(request):
    if request.method=="POST":
        print("This is post")
        title = request.POST['title']
        content = request.POST['content']
        username = request.user.username
        print(username,title,content)
        ins = Announcement(username=username,title=title,content=content)
        ins.save()
        print("written successfully")
    try:
        post_list=Announcement.objects.order_by('created_on').reverse()
        post_list_2=Announcement.objects.latest('created_on')
        test=Book.objects.all()
        context = {'post_list':post_list, 'post_list_2':post_list_2, 'test':test}
    except ObjectDoesNotExist:
        context={}
    
    return render(request, 'railapp/home.html', context)

# function for the contact us page.
def contact(request):
    if request.method=="POST":
        contact=Contact()
        name=request.POST.get('name')
        email=request.POST.get('email')
        subject=request.POST.get('subject')
        contact.name=name
        contact.email=email
        contact.subject=subject
        contact.save()

        #sends it as an email
        send_mail(
             'message from' + name,
             subject,
             email,
             ['anjoomopshora@gmail.com'],

        )
        return render(request, 'railapp/contact.html', {'name' : name})
    else:
        return render(request, 'railapp/contact.html',{})

# function for the checkout page.
def checkout(request):
    return render(request, 'railapp/checkout.html')

# function for the confirmation page.
def Confirmation(request):
    return render(request, 'railapp/confirmation.html')

# function for the FAQ page.
def faq(request):
    already_answers=Question.objects.filter(answered=True)
    without_answers=Question.objects.filter(answered=False)
    answer_contents=Answer.objects.all()
    context={
        'already_answers':already_answers,
        'without_answers':without_answers,
        'answer_contents':answer_contents
    }
    return render(request, 'railapp/faq.html', context)

# function for the userprofile dashboard
@login_required(login_url='log')  
def userprofile(request,new={}):
    username_r = request.user.username
    user_r = request.user
    book_list = Book.objects.filter(username=username_r)
    gguser = GeneralUser.objects.filter(user=user_r)
    context = { 'gguser':gguser, 'book_list':book_list }
    if book_list:
        return render(request, 'railapp/userprofile.html', context)
    else:
        context["error"] = "Sorry no buses booked"
        return render(request, 'railapp/userprofile.html', context)

# function for the trainmaster profile dashboard
@login_required(login_url='log')
def trainmasterprofile(request):
    return render(request, 'railapp/trainmasterprofile.html')

railapp/templates/railapp/checkout.html
{% extends 'railapp/main.html' %}

{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Checkout</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- library validate -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.js"></script>
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/checkout.css'%}">
</head>
<body>

<h2>Checkout Form</h2>
<div class="row">
    <div class="col-75">
        <div class="container">
            <form id="validate" action="/action_page.php">
                <div class="row">
                    <div class="col-50">
                        <h3>User Details</h3>
                        <label for="fname"><i class="fa fa-user"></i> Full Name</label>
                        <input type="text" id="fname" name="fullname" placeholder="Enter your full name" required>
                        <label for="email"><i class="fa fa-envelope"></i> Email</label>
                        <input type="text" id="email" name="email" placeholder="Enter your email" required>
                        <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
                        <input type="text" id="adr" name="address" placeholder="Enter your address" required>
                        <label for="city"><i class="fa fa-institution"></i> Phone Number</label>
                        <input type="text" id="city" name="city" placeholder="Enter your phone number" required>

                       
                    </div>

                    <div class="col-50">
                        <h3>Payment</h3>
                        <label for="fname">Accepted Cards</label>
                        <div class="icon-container">
                            <i class="fa fa-cc-visa" style="color:navy;"></i>
                            <i class="fa fa-cc-amex" style="color:blue;"></i>
                            <i class="fa fa-cc-mastercard" style="color:red;"></i>
                            
                            
                        </div>

                        <label for="cname">Name on Card</label>
                        <input type="text" id="cname" name="cardname" required>
                        <label for="ccnum">Credit card number</label>
                        <input type="text" id="ccnum" name="cardnumber"required>
                        <label for="expmonth">Exp Month</label>
                        <input type="text" id="expmonth" name="expmonth"required>
                        <div class="row">
                            <div class="col-50">
                                <label for="expyear">Exp Year</label>
                                <input type="text" id="expyear" name="expyear"required>
                            </div>
                            <div class="col-50">
                                <label for="cvv">CVV</label>
                                <input type="text" id="cvv" name="cvv" required>
                            </div>
                        </div>
                    </div>
                </div>
                
                <input type="submit" value="Continue to checkout" class="btn">
            </form>
        </div>
    </div>
    <div class="col-25">
        <div class="container">
            <h4>Purchase Details <span class="price" style="color:black"><i class="fa fa-shopping-cart"></i> <b></b></span></h4>
            <p><a href="#">Ticket</a> <span class="price">1</span></p>
            <p><a href="#">Station Number</a> <span class="price">5</span></p>
            <p><a href="#">Destination</a> <span class="price">Mirpur</span></p>
            <p><a href="#">Seat No</a> <span class="price">B12</span></p>
            <p><a href="#">Amount</a> <span class="price">BDT: 1*90</span></p>
            <hr>
            <p>Total Amount <span class="price" style="color:black"><b>BDT: 90</b></span></p>
        </div>
    </div>
</div>
<!-- script validate js -->
<script>
    $('#validate').validate({
        roles: {
            fullname: {
                required: true,
            },
            email: {
                required: true,
            },
            address: {
                required: true,
            },
            city: {
                required: true,
            },
            state: {
                required: true,
            },
            zip: {
                required: true,
            },
            cardname: {
                required: true,
            },
            cardnumber: {
                required: true,
            },
            expmonth: {
                required: true,
            },
            expyear: {
                required: true,
            },
            cvv: {
                required: true,
            },
           
        },
        messages: {
            fullname:"Please input full name*",
            email:"Please input email*",
            city:"Please input city*",
            address:"Please input address*",
            state:"Please input state*",
            zip:"Please input address*",
            cardname:"Please input card name*",
            cardnumber:"Please input card number*",
            expmonth:"Please input exp month*",
            expyear:"Please input exp year*",
            cvv:"Please input cvv*",
        },
    });
</script>
</body>
</html>
{% endblock content %}

railapp/templates/railapp/confirmation.html
{% extends 'railapp/main.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">	
		<!-- STYLE CSS -->
	<link rel="stylesheet" href="{% static 'css/contact.css' %}">
    <title>sent</title>
</head>
<body>
    <h1>Thank you You for your feedback</h1>
    <button onclick="window.location.href='{% url 'home' %}'">Return</button>
    
</body>
</html>
{% endblock content %}

railapp/templates/railapp/contact.html
{% extends 'railapp/main.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Conatct Us</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<link rel="stylesheet" href="fonts/material-design-iconic-font/css/material-design-iconic-font.min.css">	
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'css/contact.css' %}">
		<style>
		.form-group{
			display:block;
		}
		</style>
	</head>

	<body>
		{% if name %}
			<center>

				<h2>Thanks {{ name }} !</h2>
				<p>We recieved your email and will respond shortly..</p>
				<br/> <br/>
				<br/>
			</center>
		
		{% else %}
		<div class="wrapper">
			<div class="inner">
				<form class="{% url 'contact' %}" method="post">
					{% csrf_token %}
					<h3>Contact Us {{name}}</h3>
					<p>If you have any query about us please conatct us </p>
					<label class="form-group">
						<input name='name' type="text" class="form-control"  required>
						<span>Your Name</span>
						<span class="border"></span>
					</label>
					<label class="form-group">
						<input name='email' type="text" class="form-control"  required>
						<span for="">Your Mail</span>
						<span class="border"></span>
					</label>
					<label class="form-group" >
						<textarea name='subject' id="" class="form-control" required></textarea>
						<span for="">Your Message</span>
						<span class="border"></span>
					</label>
					<button type="submit" class="btn
					dento-btn">Send Message</button>

					
				</form>
			</div>
		</div>
		{% endif %}
	</body>
</html>
{% endblock content %}

railapp/templates/railapp/faq.html
{% extends 'railapp/main.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FAQ</title>
    <link rel="stylesheet" href="{% static 'css/faq.css'%}" />
  </head>

  <body>
    <div class="faqs-container">
      <h1>Questions with answers:</h1>
          <ul>
              {% for question in already_answers %}
                  <li>
                      <h2>{{ question }} ..@{{ question.user }}</h2>
                      {% endfor %}
                      <br>
                      {% for answer in answer_contents %}
                          <h2>{{ answer }}..@{{answer.user}}</h2>
                      {% endfor %}
                  </li>
              
          </ul>
      <h1>Questions Without Answer</h1>
          <ul>
              {% for question in without_answers %}
              <li>
                  <h2>{{ question }}</h2>
                  <br>
                  {% for answer in question.answer_set.all %}
                      {{answer}}
                  {% endfor %}   
              </li>
              {% endfor %}
          </ul>
    </div>
    <script src="{% static 'js/faq.js'%}"></script>
  </body>
  </html>
</html>
{% endblock content %}

railapp/templates/railapp/home.html
{% extends 'railapp/main.html' %}
{% load static %}
{% block content %}
<html>
<title>Homepage</title>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/6bfc56eb45.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/homebuy.css'%}">
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
<style>
  .post{
  background-color: #343b43;
  color: rgba(209, 185, 50, 0.89);
  display: block;
  border-radius: 55px;
  margin: auto;
  padding: 1rem;
  margin-top: 2rem;
  width: 60rem;
  }
.carousel {
    position: relative;
    width: 50rem;
    margin: auto;
    margin-top: 5rem;
    margin-bottom: 1rem;
}
.row {
  background-color:rgba(209, 185, 50, 0.89);
    text-align: left;
    display: flex;
    flex-wrap: wrap;
    margin-right: 2rem;
    margin-left: 2rem;
    padding:0.5rem;
    border-radius:3rem;
}
.mainrow{
  display: inline-flex;
  color: dimgray;
}
.welcome{
  background-color: #343b43;
  color: rgba(209, 185, 50, 0.89);
  text-align: center;
  display: block;
  width: 32rem;
  -webkit-border-radius: 55px 888px;
  border-radius: 55px 888px;
  margin: auto;
  padding: 1rem;
  margin-top: 2rem;

}
.inner{
  margin-top: 3rem;
}
textarea.form-control{
  width:400px;
  margin:auto;
  margin-left: 5rem;
}
.btn {
  color:white;
  border: 1px solid; 
  padding: .375rem .75rem;
  font-size: 1rem;
  line-height: 1.5;
  border-radius: 14.25rem;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  display: block;
}
</style>

<body>

{% if request.user.is_authenticated and user.is_guser == True %}
<div class="welcome">
  <i class="fas fa-user fa-2x" style="margin-right:3px;"></i>
<h6>General User Portal</h6>  
<h3> Welcome, {{ user.username }}</h3>
</div>
{% elif request.user.is_authenticated and user.is_trainmaster == True %}
<div class="welcome">
  <i class="fas fa-users-cog fa-2x" style="margin-right:3px;"></i>
<h6>Train Master Portal</h6> 

<h3> Welcome, {{ user.username }}</h3>
</div>
{% endif %}

{% if request.user.is_authenticated and user.is_trainmaster == True %}

<div class="inner">
  <form class="{% url 'home' %}" method="post">
    {% csrf_token %}
    <h3 style="text-align:center;">Post Announcement {{name}}</h3>
    <p style="text-align:center;">If you have any announcement to make type the message in the box below. </p>
    
    <label class="form-group" >
      <input class="form-control" type="text" id="fname" name="title"><br><br>
      <textarea name='content' id="" class="form-control" required></textarea>
      <span class="border"></span>
    </label>
    <button type="submit" class="btn
    dento-btn">Post</button>

    
  </form>
</div>
{% for row in post_list %}
  <div class="post">
  <h2 style="text-align: center;">{{row.title}}</h2>
  <h5 style="text-align: right;">by {{row.username}}</h5> <br>
  <h5 style="color: aliceblue;">{{row.content}}</h5> <br>
  <small style="text-align: right;">{{row.created_on}}</small>
  </div>
  {% endfor %}
{% else %}



<div id="carouselExampleFade" class="carousel slide carousel-fade " data-ride="carousel">
  <div class="carousel-inner ">
    <div class="carousel-item active ">
      <img class="d-block w-100" src="https://www.travelmate.com.bd/wp-content/uploads/2021/05/Metro-Rail-Dhaka.jpg" alt="First slide">
    </div>
    <div class="carousel-item ">
      <img class="d-block w-100" src="https://www.taylorreaume.com/wp-content/uploads/2021/05/QR-CODE-MARKETING-1024x534.jpg" alt="Second slide">
    </div>
    <div class="carousel-item ">
      <img class="d-block w-100" src="https://nakedsecurity.sophos.com/wp-content/uploads/sites/2/2019/09/shutterstock_1110702392.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev " href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="post" style="margin-bottom: 3rem;">
  <h2 style="text-align: center;">{{post_list_2.title}}</h2><h5 style="text-align: right;">by Trainmaster <br> {{post_list_2.username}}</h5> <br>
  <h5 style="color: aliceblue;">{{post_list_2.content}}</h5> <br>
  <small style="text-align: right;">{{post_list_2.created_on}}</small>
  </div>


 






<div class="mainrow ">
  <div class="col-md-4">
  <div class="row">
  <div class="col-2 col-sm-2 mt-1 cus-i-col">
    <i class="fas fa-tags fa-2x"></i>
  </div> 
  <div class="col-10 col-sm-10">
    <h4 class="font-weight-bold">Get Train Tickets from the comfort of your home</h4>
    <p class="font-weight-bold cus-font-col-5">Book train tickets from anywhere using 
      the robust ticketing platform exclusively built to provide the passengers with pleasant ticketing experience.</p>
  </div>
  </div>
  </div> 
  <div class="col-md-4">
  <div class="row">
  <div class="col-2 col-md-2 mt-1  cus-i-col">
    <i class="far fa-clock fa-2x"></i>
  </div> 
  <div class="col-10 col-md-10">
    <h4 class="font-weight-bold">Train &amp; Ticketing related information at your fingertips</h4> 
      <p class="font-weight-bold cus-font-col-5">Checkout available seats, route information, fare information on real time basis and get your tickets in the form of QR Code.</p>
  </div>
  </div>
  </div> 
  <div class="col-md-4">
   <div class="row">
  <div class="col-2 col-md-2 mt-1  cus-i-col">
  <i class="fas fa-lock fa-2x"></i>
  </div> 
  <div class="col-10 col-md-10">
   <h4 class="font-weight-bold">Pay Securely</h4> 
  <p class="font-weight-bold cus-font-col-5">Pay using your convenient payment option. 
    Bangladesh Metro Rail supports Visa, Master &amp; Nexus Cards, Rocket and bKash Mobile Financial Services for your convenience.</p>
 </div>
 </div>
 </div>
 </div>


 {% endif %}























</body>
{% endblock content %}
</html>

railapp/templates/railapp/main.html
<!DOCTYPE html>
{% load static %}
{% url 'home' as home %}
{% url 'contact' as contact %}
{% url 'faq' as faq %}
{% url 'signup' as signup %}
{% url 'search' as search %}
{% url 'checkout' as checkout %}
{% url 'userprofile' as userprofile %}
{% url 'trainmasterprofile' as trainmasterprofile %}
{% url 'schedule' as schedule %}
{% url 'seats' as seats %}

<html>
<head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <link rel="shortcut icon" href="{% static 'images/bymetrorail.ico' %}" />
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/footer.css' %}">
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
    .navbar {
      position: relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-wrap: wrap;
      flex-wrap: wrap;
      -ms-flex-align: center;
      align-items: center;
      -ms-flex-pack: justify;
      justify-content: center;
      padding: 0.5rem 1rem;
    }
    .navbar-brand img{
        width: 150px;
        display:inline-block;
      }
    .navbar{
        box-shadow: 0px 2px 5px #777;
      }
    
    </style>
</head>

</body id = "boddy">
<div class="sticky-top">
    <nav class="navbar navbar-light bg-dark">
    
    <a class="navbar-brand" href="{% url 'home' %}"><img id="brand" src="{% static 'images/bylogometro.png' %}" alt="logo"></a>
      <ul class="mynavbar">
    
        <li class="nav-item {% if request.path == home %} current {% endif %}"><a class="navlink" href="{% url 'home' %}" data-hover="Home">Home</a></li>
        <li class="nav-item" id="hide1"><a class="navlink" href="{% url 'search' %}" data-hover="Buy Ticket">Buy Ticket</a></li>
        <li class="nav-item"><a class="navlink" href="{% url 'schedule' %}" data-hover="Schedule">Schedule</a></li>
        <li class="nav-item {% if request.path == faq %} current {% endif %}"id="hide2"><a class="navlink" href="{% url 'faq' %}" data-hover="FAQ">FAQ</a></li>
        <li class="nav-item {% if request.path == contact %} current {% endif %}"id="hide3"><a class="navlink" href="{% url 'contact' %}" data-hover="Contact Us">Contact Us</a></li>
        
        {% if request.user.is_authenticated and user.is_trainmaster != True %}
        <li class="nav-item {% if request.path == userprofile %} current {% endif %}"><a class="navlink" href="{% url 'userprofile' %}" data-hover="Profile">Profile</a></li>
        <li class="nav-item"><a class="navlink" href="{% url 'log_out' %}" data-hover="Log Out">Log Out</a></li>
        
        </ul>
        {% elif request.user.is_authenticated and user.is_trainmaster == True %}
        <li class="nav-item"><a class="navlink" href="{% url 'seats' %}" data-hover="Seats">Seats</a></li>
        <li class="nav-item {% if request.path == trainmasterprofile %} current {% endif %}"><a class="navlink" href="{% url 'trainmasterprofile' %}" data-hover="Profile">Profile</a></li>
        <li class="nav-item"><a class="navlink" href="{% url 'log_out' %}" data-hover="Log Out">Log Out</a></li>
        <script type="text/javascript"> 
          document.getElementById("hide1").style.display = "none";
          document.getElementById("hide2").style.display = "none";
          document.getElementById("hide3").style.display = "none";
        </script>
        {% else %}

        <li class="nav-item"><a class="navlink" href="{% url 'log' %}" data-hover="Login">Login</a></li>
        <li class="nav-item {% if request.path == signup %} current {% endif %}"><a class="navlink" href="{% url 'signup' %}" data-hover="Register">Register</a></li>
        {% endif %} 
        </ul>
</nav>
</div>

{% comment %} {% if request.user.is_authenticated%} {% endcomment %}

{% block content %}


</body>
{% endblock content %}


<footer>
<footer class="site-footer">
      <div class="footer-container">
        <div class="footer-row">

          <div class="col-sm-12 col-md-6"><h6 style="color:white;">About</h6>
                <p class="text-justify">
                    The Metro Rail Management System is a web-based application that will ensure all information
                    about the metro rail and routes for the public. The system facilitates the passengers to enquire
                    about the trains available based on source and destinations, booking and cancellation of tickets,
                    and checking the status of the train schedule and destination time.
                </p>
           </div>

          

          <div class="col-xs-6 col-md-3">
            <h6 style="color:white;">Our Team Members</h6>
            <ul class="footer-links">
              <li>Farhan Hasin Saad</li>
              <li>Anjoom Nur</li>
              <li>Md Faisal Ahmed </li>
            </ul>
          </div>

          
        <div class="col-xs-6 col-md-3">
                <h6 style="color:white;">Quick Links</h6>
                <ul class="footer-links">
                <li><a href="#">Home</a></li>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">About Us</a></li>
            </ul>
          </div>
          
        </div>
        <hr>
      </div>
    </div>
</footer>
</html>
 